site_name: CoLearn Docs
nav:
  - Overview: index.md
  - Use Cases:
    - Technical: technical_use_case.md
    - Business: business_use_case.md
  - Requirements: requirements.md
  - Data Flow Diagram: dfd.md
  - Entity Relationship Diagram: erd.md
  - Tech Stack: tech_stack.md
theme: material
# mkdocs serve --dev-addr=0.0.0.0:80